require("day.plugin_config.nvim_tree")
require("day.remap")
require("day.set")
require("day.plugin_config.colors")
require("day.plugin_config.telescope")
-- require("day.plugin_config.nightfox")
-- require("day.plugin_config.catpuccin")
require("day.plugin_config.lsp_config")
require("day.plugin_config.rust_config")
require("day.plugin_config.dap_config")
require("day.neovide")
-- require("day.plugin_config.formatter")
require("day.plugin_config.lualine")
require("day.plugin_config.treesitter")
require("day.plugin_config.scrolleof")
require("day.plugin_config.comment")
require("day.plugin_config.luasnip")
